### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by WuShell** [repoze/repoze.catalog#6]
Hey there. Moving some big code base here to python3 and while working on that I've noticed repoze.catalog has not support for python3 yet, so I decided to give it a try and came up with a fork that has the needed changes, here:

https://github.com/WuShell/repoze.catalog

I've tried it in a python 3.6.1 env running part of that big code base I'm working on, so far it has worked fine (as good as it was running in a 2.7.13 env)

It would be great if someone else can take a look at that fork, in case I've missed anything, before sending a pull request.

Thanks in advance for the  review!

**Comment by tseaver** [comment]
@WuShell I'd say just make the PR, so that we can do the review using the "normal" UI (there isn't a good mechanism for commenting on the diff within your repository).
